# Containerfile for building hp-scanner-driver (openSUSE Leap 15.5)
# Maintainer: c0xc
# Build: podman build -t hp-scanner-driver-opensuse-15.5-builder -f Containerfile.opensuse-15.5 .
# Run:   podman run --rm -v ./output:/build/output hp-scanner-driver-opensuse-15.5-builder [VERSION|latest]
#
# Target: openSUSE Leap 15.5 (binary-compatible with 15.3, 15.4, 15.6)

FROM opensuse/leap:15.5

RUN zypper install -y \
    gcc gcc-c++ make autoconf automake libtool pkg-config \
    cups-devel libusb-1_0-devel sane-backends-devel libjpeg-devel \
    dbus-1-devel libavahi-devel net-snmp-devel python3-devel python3-PyQt5 \
    rpm-build wget patch \
    && zypper clean

WORKDIR /build
COPY packages/ /build/packages/
COPY VERSION /build/VERSION

RUN printf '#!/bin/bash\nVERSION=${1:-latest}\nif [ "$VERSION" = "latest" ]; then\n    VERSION=$(cat /build/VERSION)\nfi\ncd /build/packages\n./build-rpm.sh $VERSION opensuse-15.5\n' > /build/build.sh && chmod +x /build/build.sh

ENTRYPOINT ["/build/build.sh"]
